Update server-essentials

diff --git a/server-essentials b/server-essentials
--- a/server-essentials
+++ b/server-essentials
@@ -5,7 +5,7 @@ MC_VERSION="1.12.2"
 if [ "$1" = "-h" ] || [ "$1" = "--help" ] || [ "$1" = "help" ] || [ "$1" = "?" ]; then
     echo "
 $(tput setaf 1)$(tput bold)Usage:$(tput sgr0) server-essentials [version]
-    $(tput bold)version:$(tput sgr0) The Minecraft server version to install (default: 1.12)
+    $(tput bold)version:$(tput sgr0) The Minecraft server version to install (default: 1.12.2)
 "
     exit 1
 fi
@@ -37,7 +37,7 @@ function clean {
 }
 
 function configure {
-    cd "$DIR" || fail "Could not find server directory :'( Create an issue on GitHub for support."
+    cd "$DIR" || fail "Could not find server directory"
     [ -f eula.txt ] || echo "eula=true" > eula.txt
 
     echo '#!/bin/bash
@@ -69,8 +69,8 @@ function jenkins {
 
     cd "$TMP" || fail "Failed to enter temp folder ($TMP)"
     (mkdir "$1" && cd "$1") || fail "Failed to create folder for $1"
-    get-file "$2/job/$1/lastSuccessfulBuild/artifact/*zip*/archive.zip" all.zip || fail "Failed to download $1 from $2 :'( Create an issue on GitHub for support."
-    (unzip all.zip > /dev/null && mv ./archive/* . && rm -fr ./archive/) || fail "Failed to unzip $1 :'( Create an issue on GitHub for support."
+    get-file "$2/job/$1/lastSuccessfulBuild/artifact/*zip*/archive.zip" all.zip || fail "Failed to download $1 from $2"
+    (unzip all.zip > /dev/null && mv ./archive/* . && rm -fr ./archive/) || fail "Failed to unzip $1"
 
     shift 2
     OUTPUT="$1"
@@ -86,9 +86,9 @@ function jenkins {
 function bukkit {
     task "Installing $1"
 
-    cd "$TMP" || fail "Failed to enter temp folder ($TMP) :'( Create an issue on GitHub for support."
-    (mkdir "$1" && cd "$1") || fail "Failed to create folder for $1 :'( Create an issue on GitHub for support."
-    get-file "https://dev.bukkit.org/projects/$2/files/latest" "$1.jar" || fail "Failed to download $1 :'( Create an issue on GitHub for support."
+    cd "$TMP" || fail "Failed to enter temp folder ($TMP)"
+    (mkdir "$1" && cd "$1") || fail "Failed to create folder for $1"
+    get-file "https://dev.bukkit.org/projects/$2/files/latest" "$1.jar" || fail "Failed to download $1"
     mv ./*.jar "$PLUGINS"
 
     taskdone
@@ -103,9 +103,9 @@ function bukkit {
 
 task "Installing Spigot $MC_VERSION from primary URL"
 get-file "https://cdn.getbukkit.org/spigot/spigot-$MC_VERSION.jar" "spigot-$MC_VERSION.jar" || {
-    taskfail "Failed to install Spigot $MC_VERSION from first URL :'( Create an issue on GitHub for support."
+    taskfail "Failed to install Spigot $MC_VERSION from first URL"
     task "Installing Spigot $MC_VERSION from secondary URL"
-    get-file "https://cdn.getbukkit.org/spigot/spigot-$MC_VERSION-R0.1-SNAPSHOT-latest.jar" "spigot-$MC_VERSION.jar" || fail "Failed to install Spigot $MC_VERSION :'( Create an issue on GitHub for support."
+    get-file "https://cdn.getbukkit.org/spigot/spigot-$MC_VERSION-R0.1-SNAPSHOT-latest.jar" "spigot-$MC_VERSION.jar" || fail "Failed to install Spigot $MC_VERSION"
 }
 taskdone
 
@@ -119,10 +119,10 @@ bukkit Vault vault
 bukkit WorldEdit worldedit
 bukkit WorldGuard worldguard
 bukkit Multiverse-Core multiverse-core
-bukkit Holographic-Displays hoographic-displays
+bukkit Holographic-Displays holographic-displays
 
 task "Installing Multiverse-NetherPortals"
-get-file "https://dev.bukkit.org/projects/multiverse-netherportals/files/772769/download" "$PLUGINS/Multiverse-NetherPortals-2.5.jar" || fail "Failed to install Multiverse-NetherPortals :'( Create an issue on GitHub for support."
+get-file "https://dev.bukkit.org/projects/multiverse-netherportals/files/772769/download" "$PLUGINS/Multiverse-NetherPortals-2.5.jar" || fail "Failed to install Multiverse-NetherPortals"
 taskdone
 
 task "Configuring"; configure; taskdone
@@ -135,9 +135,10 @@ task "Cleaning up"; clean; taskdone
 ###########################################################################
 
 
+
 echo ""
 echo "$(tput bold)Welcome to server-essentials!"
-echo "Written by Rayzr522 & ACA30"
+echo "Written by Rayzr522 & (a little but) ACA30"
 echo ""
 echo "$(tput smul)$(tput setaf 2)$(tput bold)
 Server setup complete. You can run the server with ./start.sh
