Added ViaVersion and support for downloading older versions of MC

diff --git a/server-essentials b/server-essentials
--- a/server-essentials
+++ b/server-essentials
@@ -2,6 +2,18 @@
 
 MC_VERSION="1.11.2"
 
+if [ "$1" = "-h" -o "$1" = "--help" -o "$1" = "help" -o "$1" = "?" ]; then
+    echo "
+$(tput setaf 1)$(tput bold)Usage:$(tput sgr0) server-essentials [version]
+    $(tput bold)version:$(tput sgr0) The MC version to install
+"
+    exit 1
+fi
+
+if [ ! -z "$1" ]; then
+    MC_VERSION="$1"
+fi
+
 DIR="$PWD"
 PLUGINS="$PWD/plugins/"
 TMP="$(mktemp -d -t server-essentials)"
@@ -12,6 +24,7 @@ trap "fail Cancelled install" SIGINT
 
 # Utility methods
 function fail {
+
     taskfail
     clean
 
@@ -88,12 +101,17 @@ function bukkit {
 ###########################################################################
 
 
-task "Installing Spigot $MC_VERSION"
-get-file "https://cdn.getbukkit.org/spigot/spigot-$MC_VERSION.jar" "spigot-$MC_VERSION.jar" || fail "Failed to install Spigot $MC_VERSION"
+task "Installing Spigot $MC_VERSION from primary URL"
+get-file "https://cdn.getbukkit.org/spigot/spigot-$MC_VERSION.jar" "spigot-$MC_VERSION.jar" || {
+    taskfail "Failed to install Spigot $MC_VERSION from first URL"
+    task "Installing Spigot $MC_VERSION from secondary URL"
+    get-file "https://cdn.getbukkit.org/spigot/spigot-$MC_VERSION-R0.1-SNAPSHOT-latest.jar" "spigot-$MC_VERSION.jar" || fail "Failed to install Spigot $MC_VERSION"
+}
 taskdone
 
 jenkins EssentialsX "https://ci.drtshock.net" "$PLUGINS" Essentials/target EssentialsChat/target
 jenkins ProtocolLib "http://ci.dmulloy2.net" "$PLUGINS" modules/ProtocolLib/target
+jenkins ViaVersion "http://ci.viaversion.com" "$PLUGINS" jar/target
 
 bukkit PlugMan plugman
 bukkit PermissionsEx permissionsex
